spring:
  application:
    name: product-application

# server
server:
  port: 18081
  servlet:
    context-path: /product-api/

swagger:
  title: 商品子系统
  description: 商品子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.product.application.controller
