spring:
  application:
    name: product-application

  # Spring Cloud 配置项
  cloud:
    # Spring Cloud Sentinel 配置项
    sentinel:
      transport:
        dashboard: localhost:12088
      eager: false

# server
server:
  port: 18081
  servlet:
    context-path: /product-api/



management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true

swagger:
  enable: true
  title: 商品子系统
  description: 商品子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.product.application.controller
