spring:
  application:
    name: user-application

# server
server:
  port: 18082
  servlet:
    context-path: /user-api/

swagger:
  title: 用户子系统
  description: 用户子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.user.application.controller
