spring:
  application:
    name: user-application

  # Spring Cloud 配置项
  cloud:
    # Spring Cloud Sentinel 配置项
    sentinel:
      transport:
        dashboard: localhost:12088
      eager: false

# server
server:
  port: 18082
  servlet:
    context-path: /user-api/

swagger:
  enable: true # 暂时不去掉
  title: 用户子系统
  description: 用户子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.user.application.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true
