spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

# mybatis
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.product.dataobject

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: 'admin-application' # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 提供者的协议
  protocol:
    name: dubbo
    port: -1
  # Dubbo 提供服务的扫描基础包
  scan:
    base-packages: cn.iocoder.mall.product.service
  # Dubbo 服务提供者的配置
  provider:
    filter: -exception
    ProductAttrService:
      version: 1.0.0
    ProductCategoryService:
      version: 1.0.0
    ProductSpuService:
      version: 1.0.0
    ProductBrandService:
      version: 1.0.0
    OAuth2Service:
      version: 1.0.0
    ProductSpuCollectionService:
      version: 1.0.0

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: product-producer-group

# Seata 配置项
seata:
  # Seata 注册中心配置项
  registry:
    type: nacos # 注册中心类型
    nacos:
      serverAddr: 127.0.0.1:8848 # Nacos 服务地址
      namespace: # Nacos 命名空间
      cluster: default # 使用的 Seata 分组
