spring:
  application:
    name: search-application

  # Spring Cloud 配置项
  cloud:
    # Spring Cloud Sentinel 配置项
    sentinel:
      transport:
        dashboard: localhost:12088
      eager: false

# server
server:
  port: 18086
  servlet:
    context-path: /search-api/

swagger:
  enable: false


management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true
