spring:
  application:
    name: search-application

# server
server:
  port: 18086
  servlet:
    context-path: /search-api/

swagger:
  title: 搜索子系统
  description: 搜索子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.search.application.controller
