spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_promotion?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.promotion.biz.dataobject

# dubbo
dubbo:
  application:
    name: promotion-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.promotion.biz.service
  consumer:
    ProductSpuService:
      version: 1.0.0
  provider:
    filter: -exception
    BannerService:
      version: 1.0.0
    CouponService:
      version: 1.0.0
    ProductRecommendService:
      version: 1.0.0
    PromotionActivityService:
      version: 1.0.0


# logging
logging:
  level:
    cn.iocoder.mall.promotion.dao: debug
