spring:
  application:
    name: promotion-application

# server
server:
  port: 18085
  servlet:
    context-path: /promotion-api/

swagger:
  title: 营销子系统
  description: 营销子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.promotion.application.controller
