spring:
  application:
    name: admin-application
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080

# server
server:
  port: 18083
  servlet:
    context-path: /admin-api/

management:
  endpoints:
    web:
      exposure:
        include: "*"