spring:
  application:
    name: pay-application

  # Spring Cloud 配置项
  cloud:
    # Spring Cloud Sentinel 配置项
    sentinel:
      transport:
        dashboard: localhost:12088
      eager: false

# server
server:
  port: 18084
  servlet:
    context-path: /pay-api/

swagger:
  enable: true
  title: 支付子系统
  description: 支付子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.pay.application.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true
