spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_admin?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.admin.dataobject

# dubbo
dubbo:
  application:
    name: admin-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.admin.service