# es
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 180.167.213.26:9300
      repositories:
        enable: true

# dubbo
dubbo:
  application:
    name: search-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.search.biz.service

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: search-producer-group
