spring:
  application:
    name: admin-application
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:12088
      metric:
        charset: UTF-8
      eager: false

# server
server:
  port: 18083
  servlet:
    context-path: /admin-api/

admins:
  security:
    ignore_urls: /admin-api/admins/passport/login, /admin-api/admins/file/get_qiniu_token

# qiniu
qiniu:
  access-key: YldfyUC7OewoWM63TPYTairqnq8GMJvNek9EGoID
  secret-key: zZ7Q8wwZRyaklVvkyLmVydA4WygOBqtc_gTYzalS
  bucket: onemall

swagger:
  enable: false # 暂时不去掉
