spring:
  # datasource
  datasource:
    url: jdbc:mysql://180.167.213.26:13306/mall_cart?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iocoder.mall.cart.biz.dataobject

# dubbo
dubbo:
  application:
    name: cart-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.cart.biz.service

# xxl-job
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    executor:
#      appname: cart-job-executor
#      ip:
#      port: 0
#      logpath: /Users/yunai/logs/xxl-job/
#      logretentiondays: 1
#    accessToken:

# rocketmq
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: cart-producer-group
